# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wsz/lodge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wsz/lodge/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wsz/lodge/build/CMakeFiles /home/wsz/lodge/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wsz/lodge/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named btree

# Build rule for target.
btree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 btree
.PHONY : btree

# fast build rule for target.
btree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/build
.PHONY : btree/fast

#=============================================================================
# Target rules for targets named lodge

# Build rule for target.
lodge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lodge
.PHONY : lodge

# fast build rule for target.
lodge/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/build
.PHONY : lodge/fast

#=============================================================================
# Target rules for targets named betree

# Build rule for target.
betree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 betree
.PHONY : betree

# fast build rule for target.
betree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/build
.PHONY : betree/fast

#=============================================================================
# Target rules for targets named workload

# Build rule for target.
workload: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 workload
.PHONY : workload

# fast build rule for target.
workload/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workload.dir/build.make CMakeFiles/workload.dir/build
.PHONY : workload/fast

src/betree_single.o: src/betree_single.cpp.o
.PHONY : src/betree_single.o

# target to build an object file
src/betree_single.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/betree_single.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/betree_single.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/betree_single.cpp.o
.PHONY : src/betree_single.cpp.o

src/betree_single.i: src/betree_single.cpp.i
.PHONY : src/betree_single.i

# target to preprocess a source file
src/betree_single.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/betree_single.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/betree_single.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/betree_single.cpp.i
.PHONY : src/betree_single.cpp.i

src/betree_single.s: src/betree_single.cpp.s
.PHONY : src/betree_single.s

# target to generate assembly for a file
src/betree_single.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/betree_single.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/betree_single.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/betree_single.cpp.s
.PHONY : src/betree_single.cpp.s

src/mempool.o: src/mempool.cc.o
.PHONY : src/mempool.o

# target to build an object file
src/mempool.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/mempool.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/mempool.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/mempool.cc.o
.PHONY : src/mempool.cc.o

src/mempool.i: src/mempool.cc.i
.PHONY : src/mempool.i

# target to preprocess a source file
src/mempool.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/mempool.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/mempool.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/mempool.cc.i
.PHONY : src/mempool.cc.i

src/mempool.s: src/mempool.cc.s
.PHONY : src/mempool.s

# target to generate assembly for a file
src/mempool.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/mempool.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/mempool.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/mempool.cc.s
.PHONY : src/mempool.cc.s

src/nvm-common.o: src/nvm-common.cc.o
.PHONY : src/nvm-common.o

# target to build an object file
src/nvm-common.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/nvm-common.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/nvm-common.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/nvm-common.cc.o
.PHONY : src/nvm-common.cc.o

src/nvm-common.i: src/nvm-common.cc.i
.PHONY : src/nvm-common.i

# target to preprocess a source file
src/nvm-common.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/nvm-common.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/nvm-common.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/nvm-common.cc.i
.PHONY : src/nvm-common.cc.i

src/nvm-common.s: src/nvm-common.cc.s
.PHONY : src/nvm-common.s

# target to generate assembly for a file
src/nvm-common.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/src/nvm-common.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/src/nvm-common.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/src/nvm-common.cc.s
.PHONY : src/nvm-common.cc.s

test/lodge_test.o: test/lodge_test.cpp.o
.PHONY : test/lodge_test.o

# target to build an object file
test/lodge_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/test/lodge_test.cpp.o
.PHONY : test/lodge_test.cpp.o

test/lodge_test.i: test/lodge_test.cpp.i
.PHONY : test/lodge_test.i

# target to preprocess a source file
test/lodge_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/test/lodge_test.cpp.i
.PHONY : test/lodge_test.cpp.i

test/lodge_test.s: test/lodge_test.cpp.s
.PHONY : test/lodge_test.s

# target to generate assembly for a file
test/lodge_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lodge.dir/build.make CMakeFiles/lodge.dir/test/lodge_test.cpp.s
.PHONY : test/lodge_test.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btree.dir/build.make CMakeFiles/btree.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/betree.dir/build.make CMakeFiles/betree.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

test/workload.o: test/workload.cpp.o
.PHONY : test/workload.o

# target to build an object file
test/workload.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workload.dir/build.make CMakeFiles/workload.dir/test/workload.cpp.o
.PHONY : test/workload.cpp.o

test/workload.i: test/workload.cpp.i
.PHONY : test/workload.i

# target to preprocess a source file
test/workload.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workload.dir/build.make CMakeFiles/workload.dir/test/workload.cpp.i
.PHONY : test/workload.cpp.i

test/workload.s: test/workload.cpp.s
.PHONY : test/workload.s

# target to generate assembly for a file
test/workload.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workload.dir/build.make CMakeFiles/workload.dir/test/workload.cpp.s
.PHONY : test/workload.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... betree"
	@echo "... btree"
	@echo "... lodge"
	@echo "... workload"
	@echo "... src/betree_single.o"
	@echo "... src/betree_single.i"
	@echo "... src/betree_single.s"
	@echo "... src/mempool.o"
	@echo "... src/mempool.i"
	@echo "... src/mempool.s"
	@echo "... src/nvm-common.o"
	@echo "... src/nvm-common.i"
	@echo "... src/nvm-common.s"
	@echo "... test/lodge_test.o"
	@echo "... test/lodge_test.i"
	@echo "... test/lodge_test.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... test/workload.o"
	@echo "... test/workload.i"
	@echo "... test/workload.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

